<?
$PERM["obyavleniya"]["8"]="W";
$PERM["account-seller"]["8"]="W";
$PERM["account-seller"]["6"]="R";
$PERM["account-seller"]["*"]="D";
$PERM["account-buyer"]["8"]="W";
$PERM["account-buyer"]["2"]="D";
$PERM["account-buyer"]["7"]="D";
$PERM["about"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["index.php"]["5"]="W";
$PERM["search"]["5"]="W";
$PERM["/"]["*"]="R";
?>